export const AdminSelect = require('./AdminSelect')
export const DataSelect = require('./DataSelect')
export const AddBtn = require('./AddBtn')
export const ShowBy = require('./ShowBy')
export const Pagination = require('./Pagination')
export const DatePicker = require('./DatePicker')
export const TeacherSelect = require('./TeacherSelect')
export const DisplayData = require('./DisplayData')