php artisan transfer:truncate-tables
php artisan transfer:admins
php artisan transfer:clients
php artisan transfer:cabinets
php artisan transfer:requests
php artisan transfer:reports
php artisan transfer:reviews
php artisan transfer:groups
php artisan transfer:teacher-payments
php artisan transfer:teacher-emails
php artisan transfer:tasks
php artisan transfer:additional-payments
php artisan transfer:anonymous-payments
php artisan transfer:recommended-prices
php artisan transfer:lessons
php artisan transfer:photos
php artisan scout:flush
php artisan scout:reimport